# Generated by Django 3.0.1 on 2019-12-30 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jobTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='jobDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fulltime', models.BooleanField()),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=50)),
                ('contact', models.IntegerField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('jobtitle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobTitle')),
            ],
        ),
    ]
