# Generated by Django 3.0.1 on 2019-12-30 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20191230_1408'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='jobDescription',
            new_name='newJob',
        ),
    ]
